### PR TITLE
Map style options/james

### LINKED ISSUE #39: Map theme selector.
-Create theme selector
-Change pin color for each theme
- Toggle between searchbar and theme choser

### PR DESCRIPTION
**Pull request by jameslcarpino**
# Description
Ability to change map themes. 
Toggles in searchbar with theme selector
Themes change pin color/style.
Locally stores users map theme

Fixes # (issue)
#39 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Review by Devin44G — APPROVED** [review]
Looks great to me 🔥 We can make a new issue later to clean up some of the unused code. But, yeah, everything's clean looking on my end.

**Comment by jameslcarpino** [comment]
@Devin44G I can get rid of that unused code now and push up again before merge. Must have been remnants of the great conflict wars of 2020.

**Comment by Devin44G** [comment]
@JamesLCarpino Ah, the Great Conflict . . . **Vietnam flashback reel plays**

Sounds good though 👍

**Review by GeraldRyan — APPROVED** [review]
Gave a comprehensive review. Looks good.

**Pull request merged**
